# Generated by Django 4.2.3 on 2023-07-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=0)),
            ],
        ),
    ]
