# Generated by Django 4.2.3 on 2023-07-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='count',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
